# Task-03

Build a decision tree classifier to predict whether a customer will purchase a product or service based on their demographic and behavioral data. Use a dataset such as the Bank Marketing dataset from the UCI Machine Learning Repository.

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
bank_df = pd.read_csv('bank-additional-full.csv', sep=';')

# Display the first 5 rows
print('First 5 rows of the dataset:')
display(bank_df.head())

First 5 rows of the dataset:

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [9]:
# Display general information about the DataFrame
print('\nDataFrame Info:')
display(bank_df.info())

DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  str
 2   marital         41188 non-null  str
 3   education       41188 non-null  str
 4   default         41188 non-null  str
 5   housing         41188 non-null  str
 6   loan            41188 non-null  str
 7   contact         41188 non-null  str
 8   month           41188 non-null  str
 9   day_of_week     41188 non-null  str
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  str
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  str
dtypes: float64(5), int64(5), str(11)
memory usage: 6.6 MB

None

In [10]:
# Display descriptive statistics for numerical columns
print('\nDescriptive statistics for numerical columns:')
display(bank_df.describe())

Descriptive statistics for numerical columns:

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [11]:
# Identify categorical and numerical features
categorical_cols = bank_df.select_dtypes(include='object').columns.tolist()
numerical_cols = bank_df.select_dtypes(exclude='object').columns.tolist()

print(f"Categorical columns: {categorical_cols}")
print(f"Numerical columns: {numerical_cols}")

Categorical columns: ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome', 'y']
Numerical columns: ['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed']

C:\Users\dell\AppData\Local\Temp\ipykernel_20008\3033683163.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = bank_df.select_dtypes(include='object').columns.tolist()

In [12]:
# Preprocessing: Convert categorical variables to numerical using one-hot encoding
# Exclude the target variable 'y' for now
categorical_features_to_encode = [col for col in categorical_cols if col != 'y']

bank_df_encoded = pd.get_dummies(bank_df, columns=categorical_features_to_encode, drop_first=True)

# Convert the target variable 'y' to numerical (0 for 'no', 1 for 'yes')
bank_df_encoded['y'] = bank_df_encoded['y'].map({'no': 0, 'yes': 1})

print('\nFirst 5 rows of the encoded dataset:')
display(bank_df_encoded.head())

print('\nInfo of the encoded dataset:')
display(bank_df_encoded.info())

First 5 rows of the encoded dataset:

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False

Info of the encoded dataset:
<class 'pandas.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            41188 non-null  int64
 1   duration                       41188 non-null  int64
 2   campaign                       41188 non-null  int64
 3   pdays                          41188 non-null  int64
 4   previous                       41188 non-null  int64
 5   emp.var.rate                   41188 non-null  float64
 6   cons.price.idx                 41188 non-null  float64
 7   cons.conf.idx                  41188 non-null  float64
 8   euribor3m                      41188 non-null  float64
 9   nr.employed                    41188 non-null  float64
 10  y                              41188 non-null  int64
 11  job_blue-collar                41188 non-null  bool
 12  job_entrepreneur               41188 non-null  bool
 13  job_housemaid                  41188 non-null  bool
 14  job_management                 41188 non-null  bool
 15  job_retired                    41188 non-null  bool
 16  job_self-employed              41188 non-null  bool
 17  job_services                   41188 non-null  bool
 18  job_student                    41188 non-null  bool
 19  job_technician                 41188 non-null  bool
 20  job_unemployed                 41188 non-null  bool
 21  job_unknown                    41188 non-null  bool
 22  marital_married                41188 non-null  bool
 23  marital_single                 41188 non-null  bool
 24  marital_unknown                41188 non-null  bool
 25  education_basic.6y             41188 non-null  bool
 26  education_basic.9y             41188 non-null  bool
 27  education_high.school          41188 non-null  bool
 28  education_illiterate           41188 non-null  bool
 29  education_professional.course  41188 non-null  bool
 30  education_university.degree    41188 non-null  bool
 31  education_unknown              41188 non-null  bool
 32  default_unknown                41188 non-null  bool
 33  default_yes                    41188 non-null  bool
 34  housing_unknown                41188 non-null  bool
 35  housing_yes                    41188 non-null  bool
 36  loan_unknown                   41188 non-null  bool
 37  loan_yes                       41188 non-null  bool
 38  contact_telephone              41188 non-null  bool
 39  month_aug                      41188 non-null  bool
 40  month_dec                      41188 non-null  bool
 41  month_jul                      41188 non-null  bool
 42  month_jun                      41188 non-null  bool
 43  month_mar                      41188 non-null  bool
 44  month_may                      41188 non-null  bool
 45  month_nov                      41188 non-null  bool
 46  month_oct                      41188 non-null  bool
 47  month_sep                      41188 non-null  bool
 48  day_of_week_mon                41188 non-null  bool
 49  day_of_week_thu                41188 non-null  bool
 50  day_of_week_tue                41188 non-null  bool
 51  day_of_week_wed                41188 non-null  bool
 52  poutcome_nonexistent           41188 non-null  bool
 53  poutcome_success               41188 non-null  bool
dtypes: bool(43), float64(5), int64(6)
memory usage: 5.1 MB

None

In [13]:
# Split the data into features (X) and target (y)
X = bank_df_encoded.drop('y', axis=1)
y = bank_df_encoded['y']

print(f"Features (X) shape: {X.shape}")
print(f"Target (y) shape: {y.shape}")
print('\nFirst 5 rows of X:')
display(X.head())
print('\nFirst 5 values of y:')
display(y.head())

Features (X) shape: (41188, 53)
Target (y) shape: (41188,)

First 5 rows of X:

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False

First 5 values of y:

0    0
1    0
2    0
3    0
4    0
Name: y, dtype: int64

In [15]:
# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (28831, 53)
X_test shape: (12357, 53)
y_train shape: (28831,)
y_test shape: (12357,)

In [16]:
# Split the data into features (X) and target (y)
X = bank_df_encoded.drop('y', axis=1)
y = bank_df_encoded['y']

print(f"Features (X) shape: {X.shape}")
print(f"Target (y) shape: {y.shape}")
print('\nFirst 5 rows of X:')
display(X.head())
print('\nFirst 5 values of y:')
display(y.head())

Features (X) shape: (41188, 53)
Target (y) shape: (41188,)

First 5 rows of X:

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False

First 5 values of y:

0    0
1    0
2    0
3    0
4    0
Name: y, dtype: int64

In [17]:
# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (28831, 53)
X_test shape: (12357, 53)
y_train shape: (28831,)
y_test shape: (12357,)

In [18]:
# Import Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree Classifier
# Using a random_state for reproducibility
dtc = DecisionTreeClassifier(random_state=42)

# Train the model
dtc.fit(X_train, y_train)

print("Decision Tree Classifier trained successfully!")

Decision Tree Classifier trained successfully!

In [19]:
# Make predictions on the test set
y_pred = dtc.predict(X_test)

print("Predictions made on the test set.")

Predictions made on the test set.

In [20]:
# Evaluate the model
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print('\nAccuracy Score:')
print(accuracy_score(y_test, y_pred))

print('\nClassification Report:')
print(classification_report(y_test, y_pred))

print('\nConfusion Matrix:')
display(pd.DataFrame(confusion_matrix(y_test, y_pred),
                   index=['Actual No Purchase', 'Actual Purchase'],
                   columns=['Predicted No Purchase', 'Predicted Purchase']))

Accuracy Score:
0.8898599983814842

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94     10965
           1       0.51      0.53      0.52      1392

    accuracy                           0.89     12357
   macro avg       0.73      0.73      0.73     12357
weighted avg       0.89      0.89      0.89     12357


Confusion Matrix:

                    Predicted No Purchase  Predicted Purchase
Actual No Purchase                  10261                 704
Actual Purchase                       657                 735

In [21]:
# Import Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree Classifier
# Using a random_state for reproducibility
dtc = DecisionTreeClassifier(random_state=42)

# Train the model
dtc.fit(X_train, y_train)

print("Decision Tree Classifier trained successfully!")

Decision Tree Classifier trained successfully!

In [22]:
# Make predictions on the test set
y_pred = dtc.predict(X_test)

print("Predictions made on the test set.")

Predictions made on the test set.

In [23]:
# Evaluate the model
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print('\nAccuracy Score:')
print(accuracy_score(y_test, y_pred))

print('\nClassification Report:')
print(classification_report(y_test, y_pred))

print('\nConfusion Matrix:')
display(pd.DataFrame(confusion_matrix(y_test, y_pred),
                   index=['Actual No Purchase', 'Actual Purchase'],
                   columns=['Predicted No Purchase', 'Predicted Purchase']))

Accuracy Score:
0.8898599983814842

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94     10965
           1       0.51      0.53      0.52      1392

    accuracy                           0.89     12357
   macro avg       0.73      0.73      0.73     12357
weighted avg       0.89      0.89      0.89     12357


Confusion Matrix:

                    Predicted No Purchase  Predicted Purchase
Actual No Purchase                  10261                 704
Actual Purchase                       657                 735

In [24]:
# Import Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree Classifier
# Using a random_state for reproducibility
dtc = DecisionTreeClassifier(random_state=42)

# Train the model
dtc.fit(X_train, y_train)

print("Decision Tree Classifier trained successfully!")

Decision Tree Classifier trained successfully!

In [25]:
# Make predictions on the test set
y_pred = dtc.predict(X_test)

print("Predictions made on the test set.")

Predictions made on the test set.

In [26]:
# Evaluate the model
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print('\nAccuracy Score:')
print(accuracy_score(y_test, y_pred))

print('\nClassification Report:')
print(classification_report(y_test, y_pred))

print('\nConfusion Matrix:')
display(pd.DataFrame(confusion_matrix(y_test, y_pred),
                   index=['Actual No Purchase', 'Actual Purchase'],
                   columns=['Predicted No Purchase', 'Predicted Purchase']))

Accuracy Score:
0.8898599983814842

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94     10965
           1       0.51      0.53      0.52      1392

    accuracy                           0.89     12357
   macro avg       0.73      0.73      0.73     12357
weighted avg       0.89      0.89      0.89     12357


Confusion Matrix:

                    Predicted No Purchase  Predicted Purchase
Actual No Purchase                  10261                 704
Actual Purchase                       657                 735

In [27]:
# Import Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree Classifier
# Using a random_state for reproducibility
dtc = DecisionTreeClassifier(random_state=42)

# Train the model
dtc.fit(X_train, y_train)

print("Decision Tree Classifier trained successfully!")

Decision Tree Classifier trained successfully!

In [28]:
# Make predictions on the test set
y_pred = dtc.predict(X_test)

print("Predictions made on the test set.")

Predictions made on the test set.

In [29]:
# Evaluate the model
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print('\nAccuracy Score:')
print(accuracy_score(y_test, y_pred))

print('\nClassification Report:')
print(classification_report(y_test, y_pred))

print('\nConfusion Matrix:')
display(pd.DataFrame(confusion_matrix(y_test, y_pred),
                   index=['Actual No Purchase', 'Actual Purchase'],
                   columns=['Predicted No Purchase', 'Predicted Purchase']))

Accuracy Score:
0.8898599983814842

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94     10965
           1       0.51      0.53      0.52      1392

    accuracy                           0.89     12357
   macro avg       0.73      0.73      0.73     12357
weighted avg       0.89      0.89      0.89     12357


Confusion Matrix:

                    Predicted No Purchase  Predicted Purchase
Actual No Purchase                  10261                 704
Actual Purchase                       657                 735